sudo: required
dist: bionic
language: cpp

os:
  - linux

compiler:
  - clang++
  - g++

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./test/MZ_ALGOS_UT
on:
  condition: $compiler = clang++
  - llvm-profdata-6.0 merge -sparse codecov_data.profraw -o codecov_data.profdata
  - llvm-cov show -format="html" ./test/MZ_ALGOS_UT -instr-profile=codecov_data.profdata -o code_cov
